before_install:
 - sudo apt-get install texlive-font-utils
 - sudo apt-get install texlive-latex-extra
install: "pip3 install -q -r .travis-requirements.txt"
language: python
python:
 - "3.6"
# command to run tests
script: bash travis.sh